name: blaink_flutter
description: Flutter SDK for Blaink push notification and messaging platform
version: 1.1.4
homepage: https://github.com/Rashidium/blaink-flutter

environment:
  sdk: ^3.9.0

# Platform support - only iOS and Android
platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.blaink.blaink_flutter
        pluginClass: BlainkFlutterPlugin
      ios:
        pluginClass: BlainkFlutterPlugin